
(defparameter *simple-grammar* 
  '((sentence -> (noun-phrase verb-phrase))
    (noun-phrase -> (Article Noun))
    (verb-phrase -> (Verb noun-phrase))
    (Article -> the a)
    (Noun -> man ball woman table)
    (Verb -> hit took saw liked))
   "A grammar for a trivial subset of English."
)

(defparameter *bigger-grammar*
  '((sentence -> (noun-phrase verb-phrase))
    (noun-phrase -> (Article Adj* Noun PP*) (Name) (Pronoun))
    (verb-phrase -> (Verb noun-phrase PP*))
    (PP* -> () (PP PP*))
    (Adj* -> () (Adj Adj*))
    (PP -> (Prep noun-phrase))
    (Prep -> to in by with on)
    (Adj -> big little blue green adiabatic)
    (Article -> the a)
    (Name -> Pat Kim Lee Terry Robin)
    (Noun -> man ball woman table)
    (Verb -> hit took saw liked)
    (Pronoun -> he she it these those that))
)

(defvar *grammar* *simple-grammar* 
  "The grammar used by generate. Initially this is *simple grammar*
   but we can switch to other grammars."
)

(defun rule-lhs (rule)
  "The left-hand side of a rule."
  (first rule)
)

(defun rule-rhs (rule)
  "The right-hand side of a rule."
  (rest (rest rule))
)

(defun rewrites (category)
  "Return a list of the possible rewrites for this category."
  (rule-rhs (assoc category *grammar*)))
)

(defun generate (phrase)
  "Generate a random sentence or phrase"
;  (if (listp phrase)
;     (mappend #'generate phrase)
;     (let ((choices (rewrites phrase)))
;       (if (null choices)
;	 (list phrase)
;	 (generate (random-elt choices))
;       )
;     )
;  )
   (cond ((listp phrase) (mappend #'generate phrase))
      ((rewrites phrase) (generate (random-elt (rewrites phrase))))
    (t (list phrase))
   )  
)

(defun generate-tree (phrase) 
  "Generate a random sentence or phrase with a complete parse tree."
  (cond ((listp phrase) (mapcar #'generate-tree phrase))
     ((rewrites phrase)
      (cons phrase (generate-tree (random-elt (rewrites phrase)))))
     (t (list phrase))
  )
)
     
(defun mappend (fn list)
  "Append the results of calling fn on each element of list.
  Like mapcon, but uses append instead of nconc."
  (apply #'append (mapcar fn list))
)

(defun random-elt (choices)
  "Choose an element from a list at random."
  (elt choices (random (length choices)))
)

; (trace rule-lhs rule-rhs rewrites generate)	   

; (generate 'sentence)
;  0: (GENERATE SENTENCE)
;    1: (REWRITES SENTENCE)
;      2: (RULE-RHS (SENTENCE -> (NOUN-PHRASE VERB-PHRASE)))
;      2: RULE-RHS returned ((NOUN-PHRASE VERB-PHRASE))
;    1: REWRITES returned ((NOUN-PHRASE VERB-PHRASE))
;    1: (GENERATE (NOUN-PHRASE VERB-PHRASE))
;      2: (GENERATE NOUN-PHRASE)
;        3: (REWRITES NOUN-PHRASE)
;          4: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;          4: RULE-RHS returned ((ARTICLE NOUN))
;        3: REWRITES returned ((ARTICLE NOUN))
;        3: (GENERATE (ARTICLE NOUN))
;          4: (GENERATE ARTICLE)
;            5: (REWRITES ARTICLE)
;             6: (RULE-RHS (ARTICLE -> THE A))
;             6: RULE-RHS returned (THE A)
;            5: REWRITES returned (THE A)
;            5: (GENERATE A)
;             6: (REWRITES A)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE returned (A)
;          4: GENERATE returned (A)
;          4: (GENERATE NOUN)
;            5: (REWRITES NOUN)
;              6: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;              6: RULE-RHS returned (MAN BALL WOMAN TABLE)
;            5: REWRITES returned (MAN BALL WOMAN TABLE)
;            5: (GENERATE BALL)
;              6: (REWRITES BALL)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE returned (BALL)
;          4: GENERATE returned (BALL)
;        3: GENERATE returned (A BALL)
;      2: GENERATE returned (A BALL)
;      2: (GENERATE VERB-PHRASE)
;        3: (REWRITES VERB-PHRASE)
;          4: (RULE-RHS (VERB-PHRASE -> (VERB NOUN-PHRASE)))
;          4: RULE-RHS returned ((VERB NOUN-PHRASE))
;        3: REWRITES returned ((VERB NOUN-PHRASE))
;        3: (GENERATE (VERB NOUN-PHRASE))
;          4: (GENERATE VERB)
;            5: (REWRITES VERB)
;              6: (RULE-RHS (VERB -> HIT TOOK SAW LIKED))
;              6: RULE-RHS returned (HIT TOOK SAW LIKED)
;            5: REWRITES returned (HIT TOOK SAW LIKED)
;            5: (GENERATE TOOK)
;              6: (REWRITES TOOK)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE returned (TOOK)
;          4: GENERATE returned (TOOK)
;          4: (GENERATE NOUN-PHRASE)
;            5: (REWRITES NOUN-PHRASE)
;              6: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;              6: RULE-RHS returned ((ARTICLE NOUN))
;            5: REWRITES returned ((ARTICLE NOUN))
;            5: (GENERATE (ARTICLE NOUN))
;              6: (GENERATE ARTICLE)
;                7: (REWRITES ARTICLE)
;                  8: (RULE-RHS (ARTICLE -> THE A))
;                  8: RULE-RHS returned (THE A)
;                7: REWRITES returned (THE A)
;                7: (GENERATE THE)
;                  8: (REWRITES THE)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE returned (THE)
;              6: GENERATE returned (THE)
;              6: (GENERATE NOUN)
;                7: (REWRITES NOUN)
;                  8: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;                  8: RULE-RHS returned (MAN BALL WOMAN TABLE)
;                7: REWRITES returned (MAN BALL WOMAN TABLE)
;                7: (GENERATE TABLE)
;                  8: (REWRITES TABLE)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE returned (TABLE)
;              6: GENERATE returned (TABLE)
;            5: GENERATE returned (THE TABLE)
;          4: GENERATE returned (THE TABLE)
;        3: GENERATE returned (TOOK THE TABLE)
;      2: GENERATE returned (TOOK THE TABLE)
;    1: GENERATE returned (A BALL TOOK THE TABLE)
;  0: GENERATE returned (A BALL TOOK THE TABLE)
; (A BALL TOOK THE TABLE)

(setf *grammar* *bigger-grammar*)

; (generate 'sentence)
;  0: (GENERATE SENTENCE)
;    1: (REWRITES SENTENCE)
;      2: (RULE-RHS (SENTENCE -> (NOUN-PHRASE VERB-PHRASE)))
;      2: RULE-RHS returned ((NOUN-PHRASE VERB-PHRASE))
;    1: REWRITES returned ((NOUN-PHRASE VERB-PHRASE))
;    1: (GENERATE (NOUN-PHRASE VERB-PHRASE))
;      2: (GENERATE NOUN-PHRASE)
;        3: (REWRITES NOUN-PHRASE)
;          4: (RULE-RHS
;              (NOUN-PHRASE -> (ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN)))
;          4: RULE-RHS returned ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;        3: REWRITES returned ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;        3: (GENERATE (PRONOUN))
;          4: (GENERATE PRONOUN)
;            5: (REWRITES PRONOUN)
;              6: (RULE-RHS (PRONOUN -> HE SHE IT THESE THOSE THAT))
;              6: RULE-RHS returned (HE SHE IT THESE THOSE THAT)
;            5: REWRITES returned (HE SHE IT THESE THOSE THAT)
;            5: (GENERATE SHE)
;              6: (REWRITES SHE)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE returned (SHE)
;          4: GENERATE returned (SHE)
;        3: GENERATE returned (SHE)
;      2: GENERATE returned (SHE)
;      2: (GENERATE VERB-PHRASE)
;        3: (REWRITES VERB-PHRASE)
;          4: (RULE-RHS (VERB-PHRASE -> (VERB NOUN-PHRASE PP*)))
;          4: RULE-RHS returned ((VERB NOUN-PHRASE PP*))
;        3: REWRITES returned ((VERB NOUN-PHRASE PP*))
;        3: (GENERATE (VERB NOUN-PHRASE PP*))
;          4: (GENERATE VERB)
;            5: (REWRITES VERB)
;              6: (RULE-RHS (VERB -> HIT TOOK SAW LIKED))
;              6: RULE-RHS returned (HIT TOOK SAW LIKED)
;            5: REWRITES returned (HIT TOOK SAW LIKED)
;            5: (GENERATE SAW)
;              6: (REWRITES SAW)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE returned (SAW)
;          4: GENERATE returned (SAW)
;          4: (GENERATE NOUN-PHRASE)
;            5: (REWRITES NOUN-PHRASE)
;              6: (RULE-RHS
;                  (NOUN-PHRASE -> (ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN)))
;              6: RULE-RHS returned ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;            5: REWRITES returned ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;            5: (GENERATE (ARTICLE ADJ* NOUN PP*))
;              6: (GENERATE ARTICLE)
;                7: (REWRITES ARTICLE)
;                  8: (RULE-RHS (ARTICLE -> THE A))
;                  8: RULE-RHS returned (THE A)
;                7: REWRITES returned (THE A)
;                7: (GENERATE THE)
;                  8: (REWRITES THE)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE returned (THE)
;              6: GENERATE returned (THE)
;              6: (GENERATE ADJ*)
;                7: (REWRITES ADJ*)
;                  8: (RULE-RHS (ADJ* -> NIL (ADJ ADJ*)))
;                  8: RULE-RHS returned (NIL (ADJ ADJ*))
;                7: REWRITES returned (NIL (ADJ ADJ*))
;                7: (GENERATE NIL)
;                7: GENERATE returned NIL
;              6: GENERATE returned NIL
;              6: (GENERATE NOUN)
;                7: (REWRITES NOUN)
;                  8: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;                  8: RULE-RHS returned (MAN BALL WOMAN TABLE)
;                7: REWRITES returned (MAN BALL WOMAN TABLE)
;                7: (GENERATE MAN)
;                  8: (REWRITES MAN)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE returned (MAN)
;              6: GENERATE returned (MAN)
;              6: (GENERATE PP*)
;                7: (REWRITES PP*)
;                  8: (RULE-RHS (PP* -> NIL (PP PP*)))
;                  8: RULE-RHS returned (NIL (PP PP*))
;                7: REWRITES returned (NIL (PP PP*))
;                7: (GENERATE NIL)
;                7: GENERATE returned NIL
;              6: GENERATE returned NIL
;            5: GENERATE returned (THE MAN)
;          4: GENERATE returned (THE MAN)
;          4: (GENERATE PP*)
;            5: (REWRITES PP*)
;              6: (RULE-RHS (PP* -> NIL (PP PP*)))
;              6: RULE-RHS returned (NIL (PP PP*))
;            5: REWRITES returned (NIL (PP PP*))
;            5: (GENERATE (PP PP*))
;              6: (GENERATE PP)
;                7: (REWRITES PP)
;                  8: (RULE-RHS (PP -> (PREP NOUN-PHRASE)))
;                  8: RULE-RHS returned ((PREP NOUN-PHRASE))
;                7: REWRITES returned ((PREP NOUN-PHRASE))
;                7: (GENERATE (PREP NOUN-PHRASE))
;                  8: (GENERATE PREP)
;                    9: (REWRITES PREP)
;                      10: (RULE-RHS (PREP -> TO IN BY WITH ON))
;                      10: RULE-RHS returned (TO IN BY WITH ON)
;                    9: REWRITES returned (TO IN BY WITH ON)
;                    9: (GENERATE IN)
;                      10: (REWRITES IN)
;                        11: (RULE-RHS NIL)
;                        11: RULE-RHS returned NIL
;                      10: REWRITES returned NIL
;                    9: GENERATE returned (IN)
;                  8: GENERATE returned (IN)
;                  8: (GENERATE NOUN-PHRASE)
;                    9: (REWRITES NOUN-PHRASE)
;                      10: (RULE-RHS
;                           (NOUN-PHRASE -> (ARTICLE ADJ* NOUN PP*) (NAME)
;                            (PRONOUN)))
;                      10: RULE-RHS returned
;                            ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;                    9: REWRITES returned
;                         ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;                    9: (GENERATE (NAME))
;                      10: (GENERATE NAME)
;                        11: (REWRITES NAME)
;                          12: (RULE-RHS (NAME -> PAT KIM LEE TERRY ROBIN))
;                          12: RULE-RHS returned (PAT KIM LEE TERRY ROBIN)
;                        11: REWRITES returned (PAT KIM LEE TERRY ROBIN)
;                        11: (GENERATE LEE)
;                          12: (REWRITES LEE)
;                            13: (RULE-RHS NIL)
;                            13: RULE-RHS returned NIL
;                          12: REWRITES returned NIL
;                        11: GENERATE returned (LEE)
;                      10: GENERATE returned (LEE)
;                    9: GENERATE returned (LEE)
;                  8: GENERATE returned (LEE)
;                7: GENERATE returned (IN LEE)
;              6: GENERATE returned (IN LEE)
;              6: (GENERATE PP*)
;                7: (REWRITES PP*)
;                  8: (RULE-RHS (PP* -> NIL (PP PP*)))
;                  8: RULE-RHS returned (NIL (PP PP*))
;                7: REWRITES returned (NIL (PP PP*))
;                7: (GENERATE (PP PP*))
;                  8: (GENERATE PP)
;                    9: (REWRITES PP)
;                      10: (RULE-RHS (PP -> (PREP NOUN-PHRASE)))
;                      10: RULE-RHS returned ((PREP NOUN-PHRASE))
;                    9: REWRITES returned ((PREP NOUN-PHRASE))
;                    9: (GENERATE (PREP NOUN-PHRASE))
;                      10: (GENERATE PREP)
;                        11: (REWRITES PREP)
;                          12: (RULE-RHS (PREP -> TO IN BY WITH ON))
;                          12: RULE-RHS returned (TO IN BY WITH ON)
;                        11: REWRITES returned (TO IN BY WITH ON)
;                        11: (GENERATE WITH)
;                          12: (REWRITES WITH)
;                            13: (RULE-RHS NIL)
;                            13: RULE-RHS returned NIL
;                          12: REWRITES returned NIL
;                        11: GENERATE returned (WITH)
;                      10: GENERATE returned (WITH)
;                      10: (GENERATE NOUN-PHRASE)
;                        11: (REWRITES NOUN-PHRASE)
;                          12: (RULE-RHS
;                               (NOUN-PHRASE -> (ARTICLE ADJ* NOUN PP*) (NAME)
;                                (PRONOUN)))
;                          12: RULE-RHS returned
;                                ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;                        11: REWRITES returned
;                              ((ARTICLE ADJ* NOUN PP*) (NAME) (PRONOUN))
;                        11: (GENERATE (PRONOUN))
;                          12: (GENERATE PRONOUN)
;                            13: (REWRITES PRONOUN)
;                              14: (RULE-RHS
;                                   (PRONOUN -> HE SHE IT THESE THOSE THAT))
;                              14: RULE-RHS returned (HE SHE IT THESE THOSE THAT)
;                            13: REWRITES returned (HE SHE IT THESE THOSE THAT)
;                            13: (GENERATE SHE)
;                              14: (REWRITES SHE)
;                                15: (RULE-RHS NIL)
;                                15: RULE-RHS returned NIL
;                              14: REWRITES returned NIL
;                            13: GENERATE returned (SHE)
;                          12: GENERATE returned (SHE)
;                        11: GENERATE returned (SHE)
;                      10: GENERATE returned (SHE)
;                    9: GENERATE returned (WITH SHE)
;                  8: GENERATE returned (WITH SHE)
;                  8: (GENERATE PP*)
;                    9: (REWRITES PP*)
;                      10: (RULE-RHS (PP* -> NIL (PP PP*)))
;                      10: RULE-RHS returned (NIL (PP PP*))
;                    9: REWRITES returned (NIL (PP PP*))
;                    9: (GENERATE NIL)
;                    9: GENERATE returned NIL
;                  8: GENERATE returned NIL
;                7: GENERATE returned (WITH SHE)
;              6: GENERATE returned (WITH SHE)
;            5: GENERATE returned (IN LEE WITH SHE)
;          4: GENERATE returned (IN LEE WITH SHE)
;        3: GENERATE returned (SAW THE MAN IN LEE WITH SHE)
;      2: GENERATE returned (SAW THE MAN IN LEE WITH SHE)
;    1: GENERATE returned (SHE SAW THE MAN IN LEE WITH SHE)
;  0: GENERATE returned (SHE SAW THE MAN IN LEE WITH SHE)
;(SHE SAW THE MAN IN LEE WITH SHE)


; (generate-tree 'sentence)
;  (SENTENCE (NOUN-PHRASE (ARTICLE THE) (NOUN TABLE))
;   (VERB-PHRASE (VERB HIT) (NOUN-PHRASE (ARTICLE A) (NOUN WOMAN))))

; (generate-tree 'sentence)
;  0: (GENERATE-TREE SENTENCE)
;    1: (REWRITES SENTENCE)
;      2: (RULE-RHS (SENTENCE -> (NOUN-PHRASE VERB-PHRASE)))
;      2: RULE-RHS returned ((NOUN-PHRASE VERB-PHRASE))
;    1: REWRITES returned ((NOUN-PHRASE VERB-PHRASE))
;    1: (REWRITES SENTENCE)
;      2: (RULE-RHS (SENTENCE -> (NOUN-PHRASE VERB-PHRASE)))
;      2: RULE-RHS returned ((NOUN-PHRASE VERB-PHRASE))
;    1: REWRITES returned ((NOUN-PHRASE VERB-PHRASE))
;    1: (GENERATE-TREE (NOUN-PHRASE VERB-PHRASE))
;      2: (GENERATE-TREE NOUN-PHRASE)
;        3: (REWRITES NOUN-PHRASE)
;          4: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;          4: RULE-RHS returned ((ARTICLE NOUN))
;        3: REWRITES returned ((ARTICLE NOUN))
;        3: (REWRITES NOUN-PHRASE)
;          4: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;          4: RULE-RHS returned ((ARTICLE NOUN))
;        3: REWRITES returned ((ARTICLE NOUN))
;        3: (GENERATE-TREE (ARTICLE NOUN))
;          4: (GENERATE-TREE ARTICLE)
;            5: (REWRITES ARTICLE)
;              6: (RULE-RHS (ARTICLE -> THE A))
;              6: RULE-RHS returned (THE A)
;            5: REWRITES returned (THE A)
;            5: (REWRITES ARTICLE)
;              6: (RULE-RHS (ARTICLE -> THE A))
;              6: RULE-RHS returned (THE A)
;            5: REWRITES returned (THE A)
;            5: (GENERATE-TREE A)
;              6: (REWRITES A)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE-TREE returned (A)
;          4: GENERATE-TREE returned (ARTICLE A)
;          4: (GENERATE-TREE NOUN)
;            5: (REWRITES NOUN)
;              6: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;              6: RULE-RHS returned (MAN BALL WOMAN TABLE)
;            5: REWRITES returned (MAN BALL WOMAN TABLE)
;            5: (REWRITES NOUN)
;              6: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;              6: RULE-RHS returned (MAN BALL WOMAN TABLE)
;            5: REWRITES returned (MAN BALL WOMAN TABLE)
;            5: (GENERATE-TREE BALL)
;              6: (REWRITES BALL)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE-TREE returned (BALL)
;          4: GENERATE-TREE returned (NOUN BALL)
;        3: GENERATE-TREE returned ((ARTICLE A) (NOUN BALL))
;      2: GENERATE-TREE returned (NOUN-PHRASE (ARTICLE A) (NOUN BALL))
;      2: (GENERATE-TREE VERB-PHRASE)
;        3: (REWRITES VERB-PHRASE)
;          4: (RULE-RHS (VERB-PHRASE -> (VERB NOUN-PHRASE)))
;          4: RULE-RHS returned ((VERB NOUN-PHRASE))
;        3: REWRITES returned ((VERB NOUN-PHRASE))
;        3: (REWRITES VERB-PHRASE)
;          4: (RULE-RHS (VERB-PHRASE -> (VERB NOUN-PHRASE)))
;          4: RULE-RHS returned ((VERB NOUN-PHRASE))
;        3: REWRITES returned ((VERB NOUN-PHRASE))
;        3: (GENERATE-TREE (VERB NOUN-PHRASE))
;          4: (GENERATE-TREE VERB)
;            5: (REWRITES VERB)
;              6: (RULE-RHS (VERB -> HIT TOOK SAW LIKED))
;              6: RULE-RHS returned (HIT TOOK SAW LIKED)
;            5: REWRITES returned (HIT TOOK SAW LIKED)
;            5: (REWRITES VERB)
;              6: (RULE-RHS (VERB -> HIT TOOK SAW LIKED))
;              6: RULE-RHS returned (HIT TOOK SAW LIKED)
;            5: REWRITES returned (HIT TOOK SAW LIKED)
;            5: (GENERATE-TREE TOOK)
;              6: (REWRITES TOOK)
;                7: (RULE-RHS NIL)
;                7: RULE-RHS returned NIL
;              6: REWRITES returned NIL
;            5: GENERATE-TREE returned (TOOK)
;          4: GENERATE-TREE returned (VERB TOOK)
;          4: (GENERATE-TREE NOUN-PHRASE)
;            5: (REWRITES NOUN-PHRASE)
;              6: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;              6: RULE-RHS returned ((ARTICLE NOUN))
;            5: REWRITES returned ((ARTICLE NOUN))
;            5: (REWRITES NOUN-PHRASE)
;              6: (RULE-RHS (NOUN-PHRASE -> (ARTICLE NOUN)))
;              6: RULE-RHS returned ((ARTICLE NOUN))
;            5: REWRITES returned ((ARTICLE NOUN))
;            5: (GENERATE-TREE (ARTICLE NOUN))
;              6: (GENERATE-TREE ARTICLE)
;                7: (REWRITES ARTICLE)
;                  8: (RULE-RHS (ARTICLE -> THE A))
;                  8: RULE-RHS returned (THE A)
;                7: REWRITES returned (THE A)
;                7: (REWRITES ARTICLE)
;                  8: (RULE-RHS (ARTICLE -> THE A))
;                  8: RULE-RHS returned (THE A)
;                7: REWRITES returned (THE A)
;                7: (GENERATE-TREE A)
;                  8: (REWRITES A)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE-TREE returned (A)
;              6: GENERATE-TREE returned (ARTICLE A)
;              6: (GENERATE-TREE NOUN)
;                7: (REWRITES NOUN)
;                  8: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;                  8: RULE-RHS returned (MAN BALL WOMAN TABLE)
;                7: REWRITES returned (MAN BALL WOMAN TABLE)
;                7: (REWRITES NOUN)
;                  8: (RULE-RHS (NOUN -> MAN BALL WOMAN TABLE))
;                  8: RULE-RHS returned (MAN BALL WOMAN TABLE)
;                7: REWRITES returned (MAN BALL WOMAN TABLE)
;                7: (GENERATE-TREE MAN)
;                  8: (REWRITES MAN)
;                    9: (RULE-RHS NIL)
;                    9: RULE-RHS returned NIL
;                  8: REWRITES returned NIL
;                7: GENERATE-TREE returned (MAN)
;              6: GENERATE-TREE returned (NOUN MAN)
;            5: GENERATE-TREE returned ((ARTICLE A) (NOUN MAN))
;          4: GENERATE-TREE returned (NOUN-PHRASE (ARTICLE A) (NOUN MAN))
;        3: GENERATE-TREE returned
;             ((VERB TOOK) (NOUN-PHRASE (ARTICLE A) (NOUN MAN)))
;      2: GENERATE-TREE returned
;           (VERB-PHRASE (VERB TOOK) (NOUN-PHRASE (ARTICLE A) (NOUN MAN)))
;    1: GENERATE-TREE returned
;         ((NOUN-PHRASE (ARTICLE A) (NOUN BALL))
;          (VERB-PHRASE (VERB TOOK) (NOUN-PHRASE (ARTICLE A) (NOUN MAN))))
;  0: GENERATE-TREE returned
;       (SENTENCE (NOUN-PHRASE (ARTICLE A) (NOUN BALL))
;        (VERB-PHRASE (VERB TOOK) (NOUN-PHRASE (ARTICLE A) (NOUN MAN))))
;(SENTENCE (NOUN-PHRASE (ARTICLE A) (NOUN BALL))
; (VERB-PHRASE (VERB TOOK) (NOUN-PHRASE (ARTICLE A) (NOUN MAN))))

